runtime: custom
env: flex
entrypoint: /usr/bin/supervisord -c /app/supervisord.conf

runtime_config:
  python_version: 3.6

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

readiness_check:
  path: "/ready"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1000

env_variables:
  FLASK_APP: /app/base/__init__.py
  VERSION: staging-0-0

beta_settings:
    cloud_sql_instances: upvote-189514:us-central1:upvote
